### Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!apt-get install unrar tree

### Data Unzip

In [ ]:
!unrar x /content/drive/MyDrive/TUKL/data_online_line_width_alpha.rar /content/
!mv /content/data_online_line_width_alpha/ /content/hwd/

In [ ]:
!tree -L 2 /content/

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tree is already the newest version (2.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
/content/
├── drive
│   ├── MyDrive
│   └── Shareddrives
├── hwd
│   ├── aux_cache
│   ├── DATA_CARD.md
│   ├── Dataset
│   ├── main_1000.csv
│   ├── main_1500.csv
│   ├── main_2000.csv
│   ├── main_2500.csv
│   ├── main_3000.csv
│   ├── main_3500.csv
│   ├── main_5000.csv
│   ├── main_6000.csv
│   ├── test_cache
│   ├── test_cache2
│   ├── test_cache3
│   ├── test.csv
│   ├── test_extended.csv
│   ├── test_leakproof.csv
│   ├── test_leakproof_raw.csv
│   ├── train_cache
│   ├── train_cache2
│   ├── train_cache3
│   ├── train.csv
│   ├── train_extended.csv
│   ├── train_leakproof.csv
│   ├── train_leakproof_raw.csv
│   ├── val_cache
│   ├── val_cache3
│   ├── val.csv
│   ├── val_extended.csv
│   ├── val_leakproof.csv
│   └── val_leakproof_raw.csv
└── sample_data
    ├── anscombe.json
    ├── california_housing_test.csv
    ├── california_housing_train.csv
    ├── mnist_test.csv
    ├── mnist_train_small.csv
    └── README.md

15 directories, 27 files

In [18]:
import pandas as pd

data = pd.read_csv('/content/hwd/main_1000.csv')
data.head()

,id,gender,age,csv,img,line
0,0,f,19,Dataset/Data_1000/csv/csv_0000_0.csv,Dataset/Data_1000/img/img_0000_0.png,کے درمیان رہنے کا امکان ہے۔ رواں مالی سال 2010-11
1,0,f,19,Dataset/Data_1000/csv/csv_0000_1.csv,Dataset/Data_1000/img/img_0000_1.png,سب سے بڑا ہوں۔ (۶۴)ذکر سے جنت میں گھر تعمیر
2,0,f,19,Dataset/Data_1000/csv/csv_0000_2.csv,Dataset/Data_1000/img/img_0000_2.png,لاہور( پ ر)پاکستان مسلم لیگ (ن) اوورسیز کے مرکزی
3,0,f,19,Dataset/Data_1000/csv/csv_0000_3.csv,Dataset/Data_1000/img/img_0000_3.png,سیکرٹری آئما خطباء نے حکومت سے مطالبہ کیا کہ ش...
4,0,f,19,Dataset/Data_1000/csv/csv_0000_4.csv,Dataset/Data_1000/img/img_0000_4.png,لیں ، قبائلی رہنماوٴں نے سینیٹ میں شمالی وزیر ...

In [19]:
data2 = pd.read_csv('/content/hwd/Dataset/Data_1000/csv/csv_0000_0.csv')
data2.head()

,X cood.,Y cood.,Pressure,Height,X tilt,Y tilt,Thickness,Time,dx,dy,...,dvy,acceleration,dtheta,curvature,pen_down,stroke_id,time_norm,stroke_time,stroke_duration,stroke_time_norm
0,14597,641,0,-32,-100,3500,0,0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0,0,0.000000,0,431,0.000000
1,14588,637,0,-31,-100,3500,0,2,-9.0,-4.0,...,-2.0,4.924429,-2.723368,-0.276516,0,0,0.000046,2,431,0.004640
2,14582,628,0,-31,-100,3500,0,4,-6.0,-9.0,...,-2.5,2.915476,0.564569,0.052194,0,0,0.000093,4,431,0.009281
3,14578,617,0,-30,0,3500,0,6,-4.0,-11.0,...,-1.0,1.414214,0.239232,0.020439,0,0,0.000139,6,431,0.013921
4,14576,604,0,-30,0,3500,0,8,-2.0,-13.0,...,-1.0,1.414214,0.196122,0.014911,0,0,0.000185,8,431,0.018561