### Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!apt-get install unrar tree

### Data Unzip

In [ ]:
!unrar x /content/drive/MyDrive/TUKL/data_online_line_width_alpha.rar /content/
!mv /content/data_online_line_width_alpha/ /content/hwd/

In [21]:
!tree -L 1 /content/hwd/

/content/hwd/
├── aux_cache
├── DATA_CARD.md
├── Dataset
├── main_1000.csv
├── main_1500.csv
├── main_2000.csv
├── main_2500.csv
├── main_3000.csv
├── main_3500.csv
├── main_5000.csv
├── main_6000.csv
├── test_cache
├── test_cache2
├── test_cache3
├── test.csv
├── test_extended.csv
├── test_leakproof.csv
├── test_leakproof_raw.csv
├── train_cache
├── train_cache2
├── train_cache3
├── train.csv
├── train_extended.csv
├── train_leakproof.csv
├── train_leakproof_raw.csv
├── val_cache
├── val_cache3
├── val.csv
├── val_extended.csv
├── val_leakproof.csv
└── val_leakproof_raw.csv

10 directories, 21 files

In [18]:
import pandas as pd

data = pd.read_csv('/content/hwd/main_1000.csv')
data.head()

,id,gender,age,csv,img,line
0,0,f,19,Dataset/Data_1000/csv/csv_0000_0.csv,Dataset/Data_1000/img/img_0000_0.png,کے درمیان رہنے کا امکان ہے۔ رواں مالی سال 2010-11
1,0,f,19,Dataset/Data_1000/csv/csv_0000_1.csv,Dataset/Data_1000/img/img_0000_1.png,سب سے بڑا ہوں۔ (۶۴)ذکر سے جنت میں گھر تعمیر
2,0,f,19,Dataset/Data_1000/csv/csv_0000_2.csv,Dataset/Data_1000/img/img_0000_2.png,لاہور( پ ر)پاکستان مسلم لیگ (ن) اوورسیز کے مرکزی
3,0,f,19,Dataset/Data_1000/csv/csv_0000_3.csv,Dataset/Data_1000/img/img_0000_3.png,سیکرٹری آئما خطباء نے حکومت سے مطالبہ کیا کہ ش...
4,0,f,19,Dataset/Data_1000/csv/csv_0000_4.csv,Dataset/Data_1000/img/img_0000_4.png,لیں ، قبائلی رہنماوٴں نے سینیٹ میں شمالی وزیر ...

In [26]:
data2 = pd.read_csv('/content/hwd/Dataset/Data_1000/csv/csv_0000_0.csv')
data2.head(1).T

                        0
X cood.           14597.0
Y cood.             641.0
Pressure              0.0
Height              -32.0
X tilt             -100.0
Y tilt             3500.0
Thickness             0.0
Time                  0.0
dx                    0.0
dy                    0.0
dt                    1.0
vx                    0.0
vy                    0.0
speed                 0.0
theta                 0.0
sin_theta             0.0
cos_theta             1.0
dvx                   0.0
dvy                   0.0
acceleration          0.0
dtheta                0.0
curvature             0.0
pen_down              0.0
stroke_id             0.0
time_norm             0.0
stroke_time           0.0
stroke_duration     431.0
stroke_time_norm      0.0

In [27]:
data2.dtypes

X cood.               int64
Y cood.               int64
Pressure              int64
Height                int64
X tilt                int64
Y tilt                int64
Thickness             int64
Time                  int64
dx                  float64
dy                  float64
dt                  float64
vx                  float64
vy                  float64
speed               float64
theta               float64
sin_theta           float64
cos_theta           float64
dvx                 float64
dvy                 float64
acceleration        float64
dtheta              float64
curvature           float64
pen_down              int64
stroke_id             int64
time_norm           float64
stroke_time           int64
stroke_duration       int64
stroke_time_norm    float64
dtype: object